version: '3.8'

services:
  backend:
    container_name: backend_c
    image: aceleraprojetosfjs/assistentevirtual-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
      
    volumes:
      - ./backend:/app
      - /app/node_modules

   
