version: '3.8'

services:
  backend:
    container_name: backend_c
    image: aceleraprojetosfjs/assistentevirtual-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: "sk-proj-0j1Fyd1ojTVWbhQXUZ5KT3BlbkFJnVAi8fB1gGbO5rfTUaOg"

    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules

    environment:
      - PYTHON=/usr/bin/python3
      - OPENAI_API_KEY="sk-proj-0j1Fyd1ojTVWbhQXUZ5KT3BlbkFJnVAi8fB1gGbO5rfTUaOg"

  frontend:
    container_name: frontend_c
    image: aceleraprojetosfjs/assistentevirtual-frontend:latest
    build:
      context: ./frontend    
      dockerfile: Dockerfile
    ports:
      - "3001:80"
   
