name: Assistente CICD Workflow

on:
  push:
    branches:
      - jo-dev
  pull_request:
    branches:
      - jo-dev

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Create env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Building Docker Image for Frontend
        run: docker build -t aceleraprojetosfjs/assistentevirtual-frontend:latest  --build-arg REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }} --build-arg REACT_APP_FORMS=${{ vars.REACT_APP_FORMS }} ./frontend
      - name: Building Docker Image for Backend
        run: docker build -t aceleraprojetosfjs/assistentevirtual-backend:latest ./backend

      - name: Pushing Docker Image for Frontend
        run: docker push aceleraprojetosfjs/assistentevirtual-frontend:latest

      - name: Pushing Docker Image for Backend
        run: docker push aceleraprojetosfjs/assistentevirtual-backend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Re-create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"> .env

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker Images
        run: |
          docker pull aceleraprojetosfjs/assistentevirtual-frontend:latest
          docker pull aceleraprojetosfjs/assistentevirtual-backend:latest

      - name: Deploy using Docker Compose
        run: |
          docker-compose down
          docker-compose up --build -d
        env:
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
          REACT_APP_FORMS: ${{ vars.REACT_APP_FORMS }}
