name: Assistente CI-CD Workflow.

on:
  push:
    branches:
      - 08-jo-mvp
  pull_request:
    branches:
      - 08-jo-mvp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Create env file
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Building and Pushing Docker Images
        run: docker-compose -f compose.yaml build && docker-compose -f compose.yaml push

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Images
        run: docker-compose -f compose.yaml pull

      - name: Stop and Remove Old Containers
        run: docker-compose -f compose.yaml down

      - name: Deploy Docker Containers
        run: docker-compose -f compose.yaml up -d
