name: Assistente CI-CD Workflow Devv

on:
  push:
    branches:
      - jo-dev
  pull_request:
    branches:
      - jo-dev

jobs:
  build-and-push-dev:
    runs-on: [self-hosted, aws]
    steps:
      - name: Checkout jo-dev Branch
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Create env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Building Docker Image for Frontend
        run: docker build --build-arg REACT_APP_API_URL=${{ vars.REACT_APP_API_DEV_URL }} -t aceleraprojetosfjs/assistentevirtual-frontend:dev ./frontend

      - name: Building Docker Image for Backend
        run: docker build -t aceleraprojetosfjs/assistentevirtual-backend:dev ./backend

      - name: Pushing Docker Image for Frontend
        run: docker push aceleraprojetosfjs/assistentevirtual-frontend:dev

      - name: Pushing Docker Image for Backend (jo-dev)
        run: docker push aceleraprojetosfjs/assistentevirtual-backend:dev

  deploy-dev:
    needs: build-and-push-dev
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Re-create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker Images (jo-dev)
        run: |
          docker pull aceleraprojetosfjs/assistentevirtual-frontend:dev
          docker pull aceleraprojetosfjs/assistentevirtual-backend:dev

      - name: Deploy using Docker Compose (jo-dev)
        run: |
          docker-compose down
          REACT_APP_API_URL='http://3.131.236.61:9000/' docker-compose up --build -d
