# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs



 #     steps:
#       - name: Use Node.js ${{ matrix.node-version }} in FRONTEND
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'
#       - run: npm ci
#       - run: npm run build --if-present
#       - run: npm run lint
#       - run: npm test
#       - working-directory: frontend
      
#       - name: Use Node.js ${{ matrix.node-version }} in BACKEND
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'
#       - run: npm ci
#       - run: npm run build --if-present
#       - run: npm run lint
#       - run: npm test
#       - working-directory: backend
      
      
