# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.Js CI

on:
  push:
    branches: [ "08-jo-mvp" ]
  pull_request:
    branches: [ "08-jo-mvp"  ]

jobs:
  Build-Frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies FRONTEND
        run: npm install
        working-directory: frontend

  Build-Backend:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies BACKEND
        run: npm install
        working-directory: backend

 #     steps:
#       - name: Use Node.js ${{ matrix.node-version }} in FRONTEND
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'
#       - run: npm ci
#       - run: npm run build --if-present
#       - run: npm run lint
#       - run: npm test
#       - working-directory: frontend
      
#       - name: Use Node.js ${{ matrix.node-version }} in BACKEND
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'
#       - run: npm ci
#       - run: npm run build --if-present
#       - run: npm run lint
#       - run: npm test
#       - working-directory: backend
      
      
