name: Reusable CICD Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build-and-push-production:
    if: ${{ inputs.environment == 'Production' }}
    name: Build and Push Docker Images (Production)
    runs-on: self-hosted, Production
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: jo-prod

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Create env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image for Frontend
        run: docker build --build-arg REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }} -t aceleraprojetosfjs/assistentevirtual-frontend:Production ./frontend

      - name: Build Docker Image for Backend
        run: docker build -t aceleraprojetosfjs/assistentevirtual-backend:Production ./backend

      - name: Push Docker Image for Frontend
        run: docker push aceleraprojetosfjs/assistentevirtual-frontend:Production

      - name: Push Docker Image for Backend
        run: docker push aceleraprojetosfjs/assistentevirtual-backend:Production

  build-and-push-development:
    if: ${{ inputs.environment == 'DEV' }}
    name: Build and Push Docker Images (Development)
    runs-on: self-hosted, DEV
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: jo-dev

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Create env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image for Frontend
        run: docker build --build-arg REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }} -t aceleraprojetosfjs/assistentevirtual-frontend:DEV ./frontend

      - name: Build Docker Image for Backend
        run: docker build -t aceleraprojetosfjs/assistentevirtual-backend:DEV ./backend

      - name: Push Docker Image for Frontend
        run: docker push aceleraprojetosfjs/assistentevirtual-frontend:DEV

      - name: Push Docker Image for Backend
        run: docker push aceleraprojetosfjs/assistentevirtual-backend:DEV
